In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("data/titanic.csv")

In [3]:
df.shape
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
df.isnull().sum()#每列缺失多少个,逐个判断每个格子是不是空的，返回True/False  .sum()计算有多少个True
df.isnull().sum()/len(df)*100#换算成百分比

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [5]:
df=df.dropna(subset=["Embarked"])#subset只在Embarked为空时删行，其他列不动

In [6]:
df["Age"]=df.groupby(["Pclass","Sex"])["Age"].transform(lambda s:s.fillna(s.median()))
#df.groupby(["Pclass","Sex"] 按舱位和性别分成6组
#["Age"]只看Age这一列
#.transform() 对每一组分别处理，结果放回原来的位置
#lambda s:s.fillna(s.median()) 这一组里面，空的用本组中位数填 fillna()填数 s.median()中位数

In [7]:
df["HasCabin"]=df["Cabin"].notnull().astype(int)#notnull不是空的是返回True和False  astype转型将true转化为1 false转化为0
df=df.drop(columns=["Cabin"])#drop删列

In [8]:
df.groupby("HasCabin")["Survived"].agg(["mean","count"])#groupby 按HasCabin分堆，只看Survived
#agg是聚合可以一次算两个mean是算平均数count是计算个数

              mean  count
HasCabin
0         0.299854    687
1         0.663366    202

In [9]:
#不要覆盖原始数据
df=pd.read_csv("data/titanic.csv")
df_clean=df.copy()
df_clean=df_clean.dropna(subset=["Embarked"])
df_clean["Age"]=df_clean.groupby(["Pclass","Sex"])["Age"].transform(lambda s:s.fillna(s.median()))
df_clean["HasCabin"]=df_clean["Cabin"].notnull().astype(int)
df_clean=df_clean.drop(columns=["Cabin"])
df_clean.groupby("HasCabin")["Survived"].agg(["mean","count"])
df_clean.to_csv("data/titanic_clean.csv",index=False)

In [10]:
pd.read_csv("data/titanic.csv").shape

(891, 12)

In [11]:
df_check=pd.read_csv("data/titanic.csv")
print("形状：",df_check.shape)
print("缺失总数：",df_check.isnull().sum().sum())
print(df_check.isnull().sum()[df_check.isnull().sum()>0])

形状： (891, 12)
缺失总数： 866
Age         177
Cabin       687
Embarked      2
dtype: int64

In [12]:
df_clean

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.5,1,2,W./C. 6607,23.4500,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0

In [13]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Name         889 non-null    object
 4   Sex          889 non-null    object
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64
 7   Parch        889 non-null    int64
 8   Ticket       889 non-null    object
 9   Fare         889 non-null    float64
 10  Embarked     889 non-null    object
 11  HasCabin     889 non-null    int64
dtypes: float64(2), int64(6), object(4)
memory usage: 90.3+ KB